
import { Poppins, Amatic_SC } from 'next/font/google';
import '../styles/globals.scss'
import Navbar from './components/Navbar/Navbar';
import Footer from './components/Footer/Footer';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  
}

const primary = Poppins({
  subsets: ['latin'],
  variable: '--font-primary',
  display: 'swap',
  weight: '400'
});

const secondary = Amatic_SC({
  subsets: ['latin'],
  variable: '--font-secondary',
  display: 'swap',
  weight: "400"
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${primary.variable} ${secondary.variable}`}>
      <body>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
