import { Poppins, Amatic_SC } from "next/font/google";
import "../styles/globals.scss";
import Navbar from "../components/Navbar/Navbar";
import Footer from "../components/Footer/Footer";
import ClientOnly from "../components/ClientOnly";
import AuthModal from "@/components/Auth/AuthModal";
import getCurrentUser from "./actions/getCurrentUser";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const primary = Poppins({
  subsets: ["latin"],
  variable: "--font-primary",
  display: "swap",
  weight: "400",
});

const secondary = Amatic_SC({
  subsets: ["latin"],
  variable: "--font-secondary",
  display: "swap",
  weight: "400",
});

export default async function RootLayout({ children }) {
  const currentUser = await getCurrentUser();
  console.log(currentUser, "Current user");
  return (
    <html lang="en" className={`${primary.variable} ${secondary.variable}`}>
      <body>
        <ClientOnly>
          <AuthModal />
          <Navbar />
        </ClientOnly>
        {children}
        <Footer />
      </body>
    </html>
  );
}
